"""
Executor Agent — Generates deliverable files from the finalized trip plan:
  1. PDF Itinerary (styled, day-by-day plan using ReportLab)
  2. ICS Calendar File (importable events using icalendar)
"""

from __future__ import annotations

import logging
import os
import uuid
from datetime import datetime, timedelta

from icalendar import Calendar, Event
from reportlab.lib import colors
from reportlab.lib.pagesizes import A4
from reportlab.lib.styles import getSampleStyleSheet, ParagraphStyle
from reportlab.lib.units import mm
from reportlab.platypus import (
    SimpleDocTemplate,
    Paragraph,
    Spacer,
    Table,
    TableStyle,
    HRFlowable,
)

from models import TripPlan
import config

logger = logging.getLogger("nomad_sync.executor")

# ── Color Palette ─────────────────────────────────────────────────────
BRAND_DARK_BLUE = colors.HexColor("#0B132B")
BRAND_BLUE = colors.HexColor("#3A506B")
BRAND_ACCENT = colors.HexColor("#5BC0BE")
BRAND_LIGHT = colors.HexColor("#F4F8FA")
BRAND_TEXT = colors.HexColor("#1C2541")
BRAND_GRAY = colors.HexColor("#6B7A8F")

def _header_footer(canvas, doc, plan):
    canvas.saveState()
    # Header Background
    canvas.setFillColor(BRAND_DARK_BLUE)
    canvas.rect(0, A4[1] - 40*mm, A4[0], 40*mm, fill=1, stroke=0)
    
    # Header Text
    canvas.setFillColor(colors.white)
    canvas.setFont("Helvetica-Bold", 28)
    canvas.drawString(20*mm, A4[1] - 18*mm, "NOMAD-SYNC ITINERARY")
    
    canvas.setFillColor(BRAND_ACCENT)
    canvas.setFont("Helvetica-Bold", 14)
    canvas.drawString(20*mm, A4[1] - 28*mm, f"{plan.origin.upper()} TO {plan.destination.upper()}")
    
    # Footer
    canvas.setFillColor(BRAND_GRAY)
    canvas.setFont("Helvetica", 9)
    canvas.drawCentredString(A4[0] / 2.0, 10*mm, "Generated by Nomad-Sync • Collaborative Multi-Agent Travel Engine")
    canvas.restoreState()

# ── PDF Generation ────────────────────────────────────────────────────

def _generate_pdf(plan: TripPlan, filepath: str) -> None:
    """Generate a styled PDF itinerary using ReportLab."""
    doc = SimpleDocTemplate(
        filepath,
        pagesize=A4,
        leftMargin=20 * mm,
        rightMargin=20 * mm,
        topMargin=50 * mm,
        bottomMargin=20 * mm,
    )

    styles = getSampleStyleSheet()

    # Custom styles
    title_style = ParagraphStyle(
        "NomadTitle",
        parent=styles["Title"],
        fontSize=22,
        textColor=BRAND_TEXT,
        fontName="Helvetica-Bold",
        spaceAfter=10,
        alignment=0, # Left
    )
    subtitle_style = ParagraphStyle(
        "NomadSubtitle",
        parent=styles["Normal"],
        fontSize=12,
        textColor=BRAND_GRAY,
        fontName="Helvetica",
        spaceAfter=20,
    )
    day_header_style = ParagraphStyle(
        "DayHeader",
        parent=styles["Heading2"],
        fontSize=18,
        textColor=BRAND_DARK_BLUE,
        fontName="Helvetica-Bold",
        spaceBefore=20,
        spaceAfter=10,
        borderWidth=0,
        borderPadding=0,
    )
    activity_name_style = ParagraphStyle(
        "ActivityName",
        parent=styles["Normal"],
        fontSize=12,
        textColor=BRAND_DARK_BLUE,
        fontName="Helvetica-Bold",
    )
    normal_style = ParagraphStyle(
        "NomadNormal",
        parent=styles["Normal"],
        fontSize=10,
        textColor=BRAND_TEXT,
        leading=15,
        fontName="Helvetica",
    )
    cost_style = ParagraphStyle(
        "CostStyle",
        parent=styles["Normal"],
        fontSize=11,
        textColor=BRAND_ACCENT,
        fontName="Helvetica-Bold",
    )

    elements: list = []

    # ── Intro Section ──
    elements.append(Paragraph(plan.title, title_style))
    summary_text = (
        f"<b>Trip Details:</b> {plan.num_days} Days | {plan.num_travelers} Travelers | "
        f"Budget: Rs. {plan.budget:,}<br/><br/>"
        f"{plan.summary}"
    )
    elements.append(Paragraph(summary_text, subtitle_style))
    
    elements.append(HRFlowable(width="100%", thickness=1.5, color=BRAND_ACCENT, spaceAfter=15, spaceBefore=5))

    # ── Day-by-Day ──
    for day in plan.days:
        day_title = f"Day {day.day_number} — {day.title}"
        elements.append(Paragraph(day_title, day_header_style))

        if day.accommodation:
            elements.append(Paragraph(f"<b>Stay:</b> {day.accommodation}", normal_style))
            elements.append(Spacer(1, 10))

        # Activities table
        table_data = [["Time", "Activity", "Details", "Cost"]]
        for act in day.activities:
            details_text = f"{act.description}"
            if act.location:
                details_text += f"<br/><font color='#6B7A8F'><i>📍 {act.location}</i></font>"
            if act.travel_time_to_next:
                details_text += f"<br/><font color='#6B7A8F'><i>🚗 {act.travel_time_to_next} to next</i></font>"
            
            table_data.append([
                Paragraph(act.time_slot or "—", normal_style),
                Paragraph(act.name, activity_name_style),
                Paragraph(details_text, normal_style),
                Paragraph(f"Rs. {act.estimated_cost}" if act.estimated_cost else "Free", cost_style),
            ])

        col_widths = [25*mm, 45*mm, 82*mm, 18*mm] 

        table = Table(table_data, colWidths=col_widths, repeatRows=1)
        table.setStyle(TableStyle([
            ("BACKGROUND", (0, 0), (-1, 0), BRAND_DARK_BLUE),
            ("TEXTCOLOR", (0, 0), (-1, 0), colors.white),
            ("FONTSIZE", (0, 0), (-1, 0), 11),
            ("FONTNAME", (0, 0), (-1, 0), "Helvetica-Bold"),
            ("ALIGN", (0, 0), (-1, -1), "LEFT"),
            ("VALIGN", (0, 0), (-1, -1), "TOP"),
            ("ROWBACKGROUNDS", (0, 1), (-1, -1), [colors.white, BRAND_LIGHT]),
            ("LINEABOVE", (0, 1), (-1, -1), 0.5, colors.HexColor("#E0E0E0")),
            ("LINEBELOW", (0, -1), (-1, -1), 1, BRAND_DARK_BLUE),
            ("TOPPADDING", (0, 0), (-1, -1), 10),
            ("BOTTOMPADDING", (0, 0), (-1, -1), 10),
            ("LEFTPADDING", (0, 0), (-1, -1), 8),
            ("RIGHTPADDING", (0, 0), (-1, -1), 8),
        ]))
        elements.append(table)
        elements.append(Spacer(1, 15))

    # ── Grand Total ──
    elements.append(Spacer(1, 10))
    elements.append(HRFlowable(width="100%", thickness=1.5, color=BRAND_ACCENT, spaceBefore=10, spaceAfter=10))
    elements.append(
        Paragraph(
            f"Total Estimated Cost: Rs. {plan.total_estimated_cost:,}",
            ParagraphStyle(
                "TotalCost",
                parent=styles["Normal"],
                fontSize=16,
                textColor=BRAND_DARK_BLUE,
                fontName="Helvetica-Bold",
                alignment=2, # Right
            )
        )
    )

    doc.build(
        elements,
        onFirstPage=lambda cvs, dc: _header_footer(cvs, dc, plan),
        onLaterPages=lambda cvs, dc: _header_footer(cvs, dc, plan),
    )

# ── ICS Calendar Generation ──────────────────────────────────────────

def _generate_ics(plan: TripPlan, filepath: str) -> None:
    """Generate an ICS calendar file with events for each activity."""
    cal = Calendar()
    cal.add("prodid", "-//Nomad-Sync//Travel Engine//EN")
    cal.add("version", "2.0")
    cal.add("x-wr-calname", plan.title)

    # Start from tomorrow as the trip start date
    trip_start = datetime.now().replace(
        hour=0, minute=0, second=0, microsecond=0
    ) + timedelta(days=1)

    for day in plan.days:
        day_date = trip_start + timedelta(days=day.day_number - 1)

        for act in day.activities:
            event = Event()
            event.add("summary", act.name)
            event.add(
                "description",
                f"{act.description}\n\n"
                f"Category: {act.category}\n"
                f"Estimated Cost: Rs. {act.estimated_cost}\n"
                f"Travel to next: {act.travel_time_to_next or 'N/A'}",
            )
            if act.location:
                event.add("location", act.location)

            # Parse time_slot e.g. "09:00 - 11:00"
            if act.time_slot and "-" in act.time_slot:
                try:
                    parts = act.time_slot.split("-")
                    start_h, start_m = map(int, parts[0].strip().split(":"))
                    end_h, end_m = map(int, parts[1].strip().split(":"))
                    event.add(
                        "dtstart",
                        day_date.replace(hour=start_h, minute=start_m),
                    )
                    event.add(
                        "dtend",
                        day_date.replace(hour=end_h, minute=end_m),
                    )
                except (ValueError, IndexError):
                    event.add("dtstart", day_date.replace(hour=9, minute=0))
                    event.add("dtend", day_date.replace(hour=10, minute=0))
            else:
                event.add("dtstart", day_date.replace(hour=9, minute=0))
                event.add("dtend", day_date.replace(hour=10, minute=0))

            event.add("uid", f"{uuid.uuid4()}@nomad-sync")
            cal.add_component(event)

    with open(filepath, "wb") as f:
        f.write(cal.to_ical())


# ── Main Executor Logic ──────────────────────────────────────────────

async def run_executor_agent(plan: TripPlan) -> dict[str, str]:
    """
    Generate PDF and ICS files from the finalized trip plan.
    Returns dict with trip_id, pdf_filename, and ics_filename.
    """
    trip_id = str(uuid.uuid4())[:8]
    pdf_filename = f"nomad_sync_{trip_id}.pdf"
    ics_filename = f"nomad_sync_{trip_id}.ics"
    pdf_path = os.path.join(config.OUTPUT_DIR, pdf_filename)
    ics_path = os.path.join(config.OUTPUT_DIR, ics_filename)

    logger.info(f"Executor generating files for trip {trip_id}")

    try:
        _generate_pdf(plan, pdf_path)
        logger.info(f"PDF generated: {pdf_path}")
    except Exception as e:
        logger.error(f"PDF generation failed: {e}")
        pdf_filename = ""

    try:
        _generate_ics(plan, ics_path)
        logger.info(f"ICS generated: {ics_path}")
    except Exception as e:
        logger.error(f"ICS generation failed: {e}")
        ics_filename = ""

    return {
        "trip_id": trip_id,
        "pdf_filename": pdf_filename,
        "ics_filename": ics_filename,
    }
